"""Design tokens and the generated stylesheet for the course-notes site.

Kept out of build_site.py so the palette can be tuned without reading Python.
Pygments supplies the syntax colours at build time; this module only decides
what those colours are, so a theme change never re-parses Markdown.
"""

from __future__ import annotations

from pygments.formatters import HtmlFormatter
from pygments.styles import get_style_by_name

# Two hand-tuned palettes rather than an inversion. The dark theme is a warm
# charcoal, not black, and the accent is a single restrained green used only
# for links, active states and the prompt character.
LIGHT = {
    "bg": "#fbfbfa",
    "surface": "#ffffff",
    "surface-2": "#f3f3f1",
    "border": "#dededa",
    # Meets 3:1 against the background, so a focus ring or input edge built
    # from it is visible to a low-vision reader rather than merely decorative.
    "border-strong": "#84847c",
    "text": "#1c1d1f",
    "text-muted": "#5c5f66",
    "text-faint": "#8b8f97",
    "accent": "#1a7f47",
    "accent-soft": "#e6f2ea",
    "code-bg": "#f4f4f2",
    "code-border": "#e2e2de",
    "mark": "#fdf3c8",
    "shadow": "rgba(20, 22, 26, 0.08)",
}

DARK = {
    "bg": "#14161a",
    "surface": "#1a1d22",
    "surface-2": "#22262c",
    "border": "#2c3138",
    # Same 3:1 requirement as the light theme.
    "border-strong": "#6b737e",
    "text": "#d5d9e0",
    "text-muted": "#9aa1ac",
    "text-faint": "#6f7783",
    "accent": "#5cc98b",
    "accent-soft": "#1d2b23",
    "code-bg": "#191c21",
    "code-border": "#2c3138",
    "mark": "#3a3320",
    "shadow": "rgba(0, 0, 0, 0.4)",
}

# Pygments styles are used as the source of truth for token colours, then
# remapped onto the two palettes so code never looks pasted in from elsewhere.
CODE_THEME = "one-dark"
CODE_LIGHT_THEME = "default"

# Pygments token types, flattened to CSS class names the same way its own
# HtmlFormatter does, so the stylesheet targets the markup we actually emit.
def _vars(tokens: dict, scheme: str) -> str:
    block = "\n".join(f"  --{k}: {v};" for k, v in tokens.items())
    return f'[data-theme="{scheme}"] {{\n{block}\n}}'


def _code_vars() -> str:
    """Map Pygments token colours onto both site themes.

    The light values are emitted as custom properties on :root and the dark
    values as an override inside [data-theme="dark"], so a theme switch never
    re-renders anything -- the CSS variables simply change.
    """
    from pygments.formatters.html import _get_ttype_class

    dark = get_style_by_name(CODE_THEME).styles
    light = get_style_by_name(CODE_LIGHT_THEME).styles

    light_rules: list[str] = []
    dark_rules: list[str] = []
    for token in sorted(dark, key=str):
        dark_entry = dark[token]
        dark_colour = dark_entry[0] if dark_entry else ""
        if not dark_colour:
            continue
        light_entry = light.get(token)
        light_colour = (light_entry[0] if light_entry else "") or dark_colour
        for cls in _get_ttype_class(token):
            if not cls:
                continue
            light_rules.append(f"  .hl .{cls} {{ color: {light_colour}; }}")
            dark_rules.append(
                f'  [data-theme="dark"] .hl .{cls} {{ color: #{dark_colour}; }}'
            )

    return "\n".join(light_rules) + "\n" + "\n".join(dark_rules)


def stylesheet() -> str:
    """The complete app.css, as a single string."""
    pygments_base = HtmlFormatter(style=CODE_THEME).get_style_defs(".hl")

    return f"""
/* Generated by docker/theme.py -- edit the tokens at the top, not here. */

{_vars(LIGHT, "light")}
{_vars(DARK, "dark")}

:root {{
  --sans: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;

  --header-h: 3.5rem;
  --sidebar-w: 15.5rem;
  --toc-w: 13rem;
  --measure: 68ch;

  --radius: 6px;
  --radius-lg: 10px;
  --transition: 140ms ease;
}}

{_code_vars()}

/* ---------------------------------------------------------------- reset */

*, *::before, *::after {{ box-sizing: border-box; }}

html {{
  color-scheme: light;
  scroll-behavior: smooth;
  scroll-padding-top: calc(var(--header-h) + 1.5rem);
}}
[data-theme="dark"] {{ color-scheme: dark; }}

body {{
  margin: 0;
  font-family: var(--sans);
  font-size: 1rem;
  line-height: 1.7;
  color: var(--text);
  background: var(--bg);
  -webkit-font-smoothing: antialiased;
}}

@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }}
}}

:focus-visible {{
  outline: 2px solid var(--accent);
  outline-offset: 2px;
  border-radius: 3px;
}}

.skip-link {{
  position: absolute; left: 0.5rem; top: -3rem; z-index: 100;
  padding: 0.5rem 0.9rem; border-radius: var(--radius);
  background: var(--accent); color: #fff; font-weight: 600;
  text-decoration: none; transition: top var(--transition);
}}
.skip-link:focus {{ top: 0.5rem; }}

/* --------------------------------------------------------------- header */

.site-header {{
  position: sticky; top: 0; z-index: 30;
  display: flex; align-items: center; gap: 0.75rem;
  height: var(--header-h); padding: 0 1rem;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
}}

.brand {{
  display: flex; align-items: center; gap: 0.4rem;
  font-family: var(--mono); font-size: 0.9rem; font-weight: 600;
  color: var(--text); text-decoration: none; white-space: nowrap;
}}
.brand::before {{ content: "$"; color: var(--accent); font-weight: 700; }}
.brand:hover {{ color: var(--accent); }}

.header-spacer {{ flex: 1; }}

.icon-btn {{
  display: inline-flex; align-items: center; justify-content: center;
  width: 2.25rem; height: 2.25rem; padding: 0;
  background: transparent; color: var(--text-muted);
  border: 1px solid transparent; border-radius: var(--radius);
  cursor: pointer; transition: all var(--transition);
}}
.icon-btn:hover {{
  color: var(--text); background: var(--surface-2);
  border-color: var(--border);
}}
.icon-btn svg {{ width: 1.1rem; height: 1.1rem; fill: none;
               stroke: currentColor; stroke-width: 1.75;
               stroke-linecap: round; stroke-linejoin: round; }}

#nav-toggle {{ display: none; }}

/* ----------------------------------------------------------------- shell */

.layout {{
  display: grid;
  grid-template-columns: var(--sidebar-w) minmax(0, 1fr) var(--toc-w);
  gap: 2.5rem;
  max-width: 96rem;
  margin: 0 auto;
  padding: 0 1.5rem;
  align-items: start;
}}

.sidebar {{
  position: sticky; top: var(--header-h);
  max-height: calc(100vh - var(--header-h));
  overflow-y: auto;
  padding: 1.75rem 0.5rem 2rem 0;
  font-size: 0.9rem;
}}

.nav-group + .nav-group {{ margin-top: 1.5rem; }}
.nav-group-title {{
  margin: 0 0 0.35rem; padding-left: 0.65rem;
  font-family: var(--mono); font-size: 0.7rem; font-weight: 600;
  letter-spacing: 0.09em; text-transform: uppercase;
  color: var(--text-faint);
}}

.nav-list {{ list-style: none; margin: 0; padding: 0; }}

.nav-list a {{
  display: block; padding: 0.3rem 0.65rem;
  color: var(--text-muted); text-decoration: none;
  border-left: 2px solid transparent; border-radius: 0 var(--radius) var(--radius) 0;
  transition: all var(--transition);
}}
.nav-list a:hover {{ color: var(--text); background: var(--surface-2); }}
.nav-list a.is-current {{
  color: var(--accent); font-weight: 600;
  background: var(--accent-soft);
  border-left-color: var(--accent);
}}
.nav-list .nav-path {{
  display: block; font-family: var(--mono);
  font-size: 0.72rem; color: var(--text-faint);
}}

.content {{
  min-width: 0;
  max-width: var(--measure);
  padding: 2rem 0 5rem;
}}

.breadcrumb {{
  margin: 0 0 1.5rem; font-family: var(--mono);
  font-size: 0.8rem; color: var(--text-faint);
}}
.breadcrumb a {{ color: var(--text-muted); text-decoration: none; }}
.breadcrumb a:hover {{ color: var(--accent); text-decoration: underline; }}

/* ------------------------------------------------------------ markdown */

.content h1, .content h2, .content h3,
.content h4, .content h5, .content h6 {{
  line-height: 1.25; scroll-margin-top: calc(var(--header-h) + 1.5rem);
}}
.content h1 {{
  font-size: 2rem; margin: 0 0 1.25rem;
  letter-spacing: -0.02em;
}}
.content h1::after {{
  content: ""; display: block; margin-top: 0.9rem;
  border-bottom: 1px solid var(--border);
}}
.content h2 {{
  font-size: 1.4rem; margin: 2.5rem 0 0.85rem;
  padding-bottom: 0.4rem; border-bottom: 1px solid var(--border);
}}
.content h3 {{ font-size: 1.12rem; margin: 1.9rem 0 0.6rem; }}
.content h4 {{ font-size: 1rem; margin: 1.5rem 0 0.5rem; color: var(--text-muted); }}
.content p, .content ul, .content ol {{ margin: 0 0 1.1rem; }}
.content ul, .content ol {{ padding-left: 1.5rem; }}
.content li {{ margin-bottom: 0.35rem; }}
.content li > ul, .content li > ol {{ margin-top: 0.35rem; }}

.content a {{ color: var(--accent); text-decoration-thickness: 1px;
               text-underline-offset: 2px; }}
.content a:hover {{ text-decoration-thickness: 2px; }}

.content strong {{ font-weight: 650; }}

/* Anchor link revealed on heading hover */
.content h2 a, .content h3 a, .content h4 a {{
  color: var(--text-faint); text-decoration: none;
  margin-left: 0.35rem; opacity: 0; transition: opacity var(--transition);
}}
.content h2:hover a, .content h3:hover a, .content h4:hover a {{ opacity: 1; }}

.content blockquote {{
  margin: 1.3rem 0; padding: 0.75rem 1.1rem;
  background: var(--surface-2);
  border-left: 3px solid var(--accent);
  border-radius: 0 var(--radius) var(--radius) 0;
  color: var(--text-muted);
}}
.content blockquote p:last-child {{ margin-bottom: 0; }}

.content hr {{
  border: 0; border-top: 1px solid var(--border);
  margin: 2.5rem 0;
}}

.content :not(pre) > code {{
  font-family: var(--mono); font-size: 0.87em;
  background: var(--code-bg); color: var(--text);
  padding: 0.12em 0.38em; border-radius: 4px;
  border: 1px solid var(--code-border);
  overflow-wrap: break-word;
}}

/* -------------------------------------------------------------- tables */

.table-wrap {{
  margin: 1.4rem 0; overflow-x: auto;
  border: 1px solid var(--border); border-radius: var(--radius);
}}
.content table {{ border-collapse: collapse; width: 100%; font-size: 0.93rem; }}
.content th, .content td {{
  padding: 0.55rem 0.85rem; text-align: left;
  border-bottom: 1px solid var(--border); vertical-align: top;
}}
.content thead th {{
  background: var(--surface-2); font-weight: 600;
  position: sticky; top: 0;
}}
.content tbody tr:last-child td {{ border-bottom: 0; }}
.content tbody tr:hover {{ background: var(--surface-2); }}

/* ------------------------------------------------------------ code blocks */

.code-block {{
  margin: 1.4rem 0;
  border: 1px solid var(--code-border);
  border-radius: var(--radius-lg);
  background: var(--code-bg);
  overflow: hidden;
}}

.code-head {{
  display: flex; align-items: center; justify-content: space-between;
  padding: 0.4rem 0.5rem 0.4rem 0.85rem;
  background: var(--surface-2);
  border-bottom: 1px solid var(--code-border);
  font-family: var(--mono); font-size: 0.73rem;
}}

.code-lang {{ color: var(--text-faint); text-transform: uppercase;
              letter-spacing: 0.07em; }}

.copy-btn {{
  padding: 0.22rem 0.6rem;
  font-family: var(--mono); font-size: 0.73rem;
  color: var(--text-muted); background: var(--surface);
  border: 1px solid var(--border); border-radius: 4px;
  cursor: pointer; transition: all var(--transition);
}}
.copy-btn:hover {{ color: var(--accent); border-color: var(--accent); }}
.copy-btn.copied {{ color: var(--accent); border-color: var(--accent); }}

.content pre {{
  margin: 0; padding: 0.9rem 1rem;
  overflow-x: auto;
  font-family: var(--mono); font-size: 0.85rem; line-height: 1.6;
  tab-size: 4;
}}
.content pre code {{ background: none; padding: 0; border: 0;
                     font-size: inherit; }}

/* Pygments token colours, remapped onto both themes. */
{pygments_base}
.hl {{ color: var(--text); }}
{_code_vars()}

/* --------------------------------------------------------------- images */

.content img {{
  display: block; max-width: 100%; height: auto;
  margin: 1.4rem 0; cursor: zoom-in;
  border: 1px solid var(--border); border-radius: var(--radius);
  background: var(--surface);
}}
.content img:hover {{ border-color: var(--accent); }}

.figure-caption {{
  margin: -0.9rem 0 1.4rem;
  font-size: 0.85rem; color: var(--text-faint); text-align: center;
}}

/* ------------------------------------------------------------------ pdf */

.pdf-card {{
  display: flex; align-items: center; gap: 0.9rem;
  margin: 1.4rem 0; padding: 0.9rem 1.1rem;
  background: var(--surface); text-decoration: none;
  border: 1px solid var(--border); border-radius: var(--radius-lg);
  transition: all var(--transition);
}}
.pdf-card:hover {{ border-color: var(--accent); background: var(--surface-2); }}
.pdf-badge {{
  flex-shrink: 0; padding: 0.2rem 0.5rem;
  font-family: var(--mono); font-size: 0.68rem; font-weight: 700;
  letter-spacing: 0.05em; color: #fff; background: var(--accent);
  border-radius: 4px;
}}
.pdf-text {{ flex: 1; min-width: 0; }}
.pdf-title {{ color: var(--text); font-weight: 600; }}
.pdf-meta {{ font-size: 0.83rem; color: var(--text-muted); }}
.pdf-arrow {{ color: var(--text-faint); }}

/* ------------------------------------------------------------------ toc */

.toc {{
  position: sticky; top: var(--header-h);
  max-height: calc(100vh - var(--header-h));
  overflow-y: auto;
  padding: 1.75rem 0 2rem;
  font-size: 0.83rem;
}}
.toc-title {{
  margin: 0 0 0.5rem;
  font-family: var(--mono); font-size: 0.7rem; font-weight: 600;
  letter-spacing: 0.09em; text-transform: uppercase; color: var(--text-faint);
}}
.toc-list {{ list-style: none; margin: 0; padding: 0;
             border-left: 1px solid var(--border); }}
.toc-link {{
  display: block; padding: 0.22rem 0.7rem;
  color: var(--text-muted); text-decoration: none;
  border-left: 2px solid transparent; margin-left: -1px;
  transition: all var(--transition);
}}
.toc-link:hover {{ color: var(--text); }}
.toc-link.is-active {{
  color: var(--accent); font-weight: 600; border-left-color: var(--accent);
}}
.toc-h3 {{ padding-left: 1.4rem; font-size: 0.8rem; }}

/* Mobile TOC: a disclosure above the content. */
.toc-mobile {{ display: none; margin: 0 0 1.5rem; }}
.toc-mobile > summary {{
  padding: 0.5rem 0.85rem; cursor: pointer;
  background: var(--surface-2); border: 1px solid var(--border);
  border-radius: var(--radius); font-weight: 600; font-size: 0.9rem;
  list-style: none;
}}
.toc-mobile > summary::-webkit-details-marker {{ display: none; }}
.toc-mobile > summary::before {{ content: "▸ "; color: var(--accent); }}
.toc-mobile[open] > summary::before {{ content: "▾ "; }}
.toc-mobile .toc-list {{ margin-top: 0.5rem; border-left: 0; }}
.toc-mobile .toc-link {{ padding-left: 0.85rem; border-left: 0; }}

/* ------------------------------------------- shell around a slide deck */

/* The decks position their own content in the viewport, so the shell sits in
   normal flow and the pager goes below the deck rather than above it. */
.slide-shell-top .site-header {{ position: static; border-radius: 0; }}
.slide-shell-top .breadcrumb {{ margin: 1rem 1.5rem 0; }}
.slide-shell-bottom {{ margin: 0 1.5rem 2.5rem; }}
.slide-shell-bottom .pager {{ margin-top: 0; }}

/* ---------------------------------------------------------------- pager */

.pager {{
  display: flex; gap: 1rem; margin-top: 3rem;
  padding-top: 1.5rem; border-top: 1px solid var(--border);
  font-size: 0.9rem;
}}
.pager-link {{
  flex: 1; padding: 0.7rem 0.9rem;
  background: var(--surface); border: 1px solid var(--border);
  border-radius: var(--radius); text-decoration: none;
  transition: all var(--transition);
}}
.pager-link:hover {{ border-color: var(--accent); background: var(--surface-2); }}
.pager-next {{ text-align: right; }}
.pager-label {{
  display: block; font-family: var(--mono); font-size: 0.68rem;
  letter-spacing: 0.07em; text-transform: uppercase; color: var(--text-faint);
}}
.pager-title {{ color: var(--text); font-weight: 600; }}
.pager-link:hover .pager-title {{ color: var(--accent); }}
.pager-empty {{ flex: 1; }}

/* --------------------------------------------------------------- search */

.search-dialog {{
  width: min(42rem, calc(100vw - 2rem));
  max-height: min(32rem, 80vh);
  padding: 0; border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  background: var(--surface); color: var(--text);
  box-shadow: 0 12px 40px var(--shadow);
  overflow: hidden;
}}
.search-dialog::backdrop {{ background: rgba(10, 12, 15, 0.55); }}

.search-head {{
  display: flex; align-items: center; gap: 0.6rem;
  padding: 0.75rem 1rem; border-bottom: 1px solid var(--border);
}}
.search-head svg {{ width: 1.05rem; height: 1.05rem; flex-shrink: 0;
                   fill: none; stroke: var(--text-faint); stroke-width: 2; }}
.search-input {{
  flex: 1; padding: 0.2rem 0; font: inherit; font-size: 0.95rem;
  background: transparent; color: var(--text); border: 0;
}}
.search-input:focus {{ outline: none; }}
.search-hint {{
  font-family: var(--mono); font-size: 0.7rem; color: var(--text-faint);
  padding: 0.1rem 0.35rem; border: 1px solid var(--border);
  border-radius: 3px;
}}

.search-results {{ max-height: 24rem; overflow-y: auto; margin: 0;
                   padding: 0.4rem; list-style: none; }}
.search-result {{
  padding: 0.55rem 0.7rem; border-radius: var(--radius); cursor: pointer;
}}
.search-result[aria-selected="true"] {{ background: var(--accent-soft); }}
.search-result-title {{
  display: block; font-weight: 600; font-size: 0.9rem; color: var(--text);
}}
.search-result-path {{
  display: block; font-family: var(--mono); font-size: 0.72rem;
  color: var(--text-faint); margin-bottom: 0.15rem;
}}
.search-result-text {{
  display: block; font-size: 0.85rem; color: var(--text-muted);
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}}
.search-result mark {{ background: var(--mark); color: inherit;
                       border-radius: 2px; padding: 0 0.1em; }}
.search-empty {{ padding: 1.5rem 1rem; text-align: center;
                 color: var(--text-faint); font-size: 0.9rem; }}

/* ------------------------------------------------------------- lightbox */

.lightbox {{
  border: 0; padding: 1.5rem; max-width: 96vw; max-height: 96vh;
  background: transparent; overflow: visible;
}}
.lightbox::backdrop {{ background: rgba(8, 10, 12, 0.9); }}
.lightbox img {{
  display: block; max-width: 100%; max-height: 90vh;
  margin: 0 auto; border-radius: var(--radius);
  box-shadow: 0 8px 40px var(--shadow);
}}
.lightbox-close {{
  position: absolute; top: 1rem; right: 1rem;
  width: 2.5rem; height: 2.5rem; font-size: 1.3rem; line-height: 1;
  color: #fff; background: rgba(255, 255, 255, 0.1);
  border: 1px solid rgba(255, 255, 255, 0.25);
  border-radius: 50%; cursor: pointer;
}}
.lightbox-close:hover {{ background: rgba(255, 255, 255, 0.2); }}
.lightbox-caption {{
  margin-top: 0.75rem; text-align: center;
  color: #dfe3e8; font-size: 0.88rem;
}}

.nav-scrim {{
  position: fixed; inset: 0; z-index: 25;
  background: rgba(10, 12, 15, 0.5);
  opacity: 0; pointer-events: none; transition: opacity var(--transition);
}}
body.nav-open .nav-scrim {{ opacity: 1; pointer-events: auto; }}

/* ----------------------------------------------------------- responsive */

@media (max-width: 1200px) {{
  .layout {{ grid-template-columns: var(--sidebar-w) minmax(0, 1fr); }}
  .toc {{ display: none; }}
  .toc-mobile {{ display: block; }}
}}

@media (max-width: 900px) {{
  .layout {{ grid-template-columns: minmax(0, 1fr); gap: 0; padding: 0 1.1rem; }}
  #nav-toggle {{ display: inline-flex; }}

  .sidebar {{
    position: fixed; top: 0; left: 0; bottom: 0; z-index: 26;
    width: min(17rem, 84vw);
    max-height: none; padding: 1.25rem 1rem 2rem;
    background: var(--surface); border-right: 1px solid var(--border);
    transform: translateX(-100%); transition: transform var(--transition);
    overflow-y: auto;
  }}
  body.nav-open .sidebar {{ transform: translateX(0); }}
  body.nav-open {{ overflow: hidden; }}

  .content {{ max-width: none; padding-top: 1.5rem; }}
  .content h1 {{ font-size: 1.7rem; }}
  .pager {{ flex-direction: column; }}
}}

@media (max-width: 560px) {{
  .content pre {{ font-size: 0.8rem; padding: 0.75rem 0.8rem; }}
  .content thead th {{ position: static; }}
  .pdf-card {{ flex-wrap: wrap; }}
}}

@media print {{
  .site-header, .sidebar, .toc, .toc-mobile, .pager,
  .copy-btn, .search-dialog, .nav-scrim {{ display: none !important; }}
  .layout {{ display: block; padding: 0; }}
  .content {{ max-width: none; }}
  .code-block {{ break-inside: avoid; }}
}}
"""
